# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  # Required for actions/cache on push & PR
  actions: read
  contents: read
  pull-requests: write
  # Needed by SonarCloud to publish commit statuses/checks
  statuses: write
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK
        uses: actions/setup-java@v6
        with:
          java-version: '25.0.4+101.0.LTS'
          distribution: 'temurin'
          cache: maven

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Cache SonarCloud packages
        uses: actions/cache@v6
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Create and populate ~/.testcontainers.properties
        run: |
          cat <<EOF > ~/.testcontainers.properties
          testcontainers.reuse.enable=true
          EOF

          echo "cat ~/.testcontainers.properties"
          cat ~/.testcontainers.properties

      - if: ${{ github.ref != 'refs/heads/main' }}
        name: Build and analyze
        run: ./mvnw clean verify

      - if: ${{ github.ref == 'refs/heads/main' }}
        name: Build, analyze and Image with Maven
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./mvnw -B verify sonar:sonar spring-boot:build-image --file pom.xml

